/** @type {import('stylelint').Config} */
export default {
	extends: [
		"stylelint-config-recommended-vue",
		"stylelint-config-recess-order",
		"stylelint-plugin-logical-css/configs/recommended",
	],
	ignoreFiles: ["dist/**"],
	plugins: [
		"@stylistic/stylelint-plugin",
		"stylelint-high-performance-animation",
		"stylelint-use-nesting",
		"stylelint-plugin-use-baseline",
		"stylelint-prettier",
	],
	rules: {
		"@stylistic/color-hex-case": "lower",
		"@stylistic/number-leading-zero": "always",
		"@stylistic/unit-case": "lower",
		"alpha-value-notation": "percentage",
		"color-function-notation": "modern",
		"color-named": "never",
		"csstools/use-nesting": "always",
		"declaration-block-no-shorthand-property-overrides": true,
		"display-notation": "full",
		"font-weight-notation": "numeric",
		"hue-degree-notation": "angle",
		"length-zero-no-unit": true,
		"media-feature-range-notation": "context",
		"no-descending-specificity": true,
		"plugin/no-low-performance-animation-properties": [true, { severity: "warning" }],
		"plugin/use-baseline": [true, { available: "newly" }],
		"prettier/prettier": true,
	},
};
